# Generated by Django 5.1.4 on 2024-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_paragraph', models.TextField()),
                ('processed_paragraph', models.TextField(editable=False)),
                ('image', models.ImageField(upload_to='creative/')),
                ('header', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_paragraph', models.TextField()),
                ('processed_paragraph', models.TextField(editable=False)),
                ('image', models.ImageField(upload_to='technical/')),
                ('header', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
