# Generated by Django 5.1.4 on 2024-12-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='creative',
            name='processed_paragraph',
        ),
        migrations.RemoveField(
            model_name='creative',
            name='raw_paragraph',
        ),
        migrations.RemoveField(
            model_name='technical',
            name='processed_paragraph',
        ),
        migrations.RemoveField(
            model_name='technical',
            name='raw_paragraph',
        ),
    ]
