# Generated by Django 5.1.4 on 2024-12-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_creativeachievements_technicalachievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
